! This automatically generated Fortran wrapper file allows codes
! written in Fortran to be called directly from C and translates all
! C-style arguments into expected Fortran-style arguments (with
! assumed size, local type declarations, etc.).


MODULE C_SHADOWING_MODULE
  IMPLICIT NONE


CONTAINS


  
  SUBROUTINE C_MU(NORMALS_DIM_1, NORMALS_DIM_2, NORMALS, S_DIM_1, S, MU_I_DIM_1, MU_I) BIND(C)
    USE SHADOWING_MODULE, ONLY: MU
    IMPLICIT NONE
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: NORMALS_DIM_1
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: NORMALS_DIM_2
    REAL(KIND=KIND ( 0.0D0 )), INTENT(IN), DIMENSION(NORMALS_DIM_1,NORMALS_DIM_2) :: NORMALS
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: S_DIM_1
    REAL(KIND=KIND ( 0.0D0 )), INTENT(IN), DIMENSION(S_DIM_1) :: S
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: MU_I_DIM_1
    REAL(KIND=KIND ( 0.0D0 )), INTENT(OUT), DIMENSION(MU_I_DIM_1) :: MU_I
  
    CALL MU(NORMALS, S, MU_I)
  END SUBROUTINE C_MU
  

  
  SUBROUTINE C_NON(MU_I_DIM_1, MU_I, MU_E_DIM_1, MU_E, NU_I_DIM_1, NU_I, NU_E_DIM_1, NU_E) BIND(C)
    USE SHADOWING_MODULE, ONLY: NON
    IMPLICIT NONE
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: MU_I_DIM_1
    REAL(KIND=KIND ( 0.0D0 )), INTENT(IN), DIMENSION(MU_I_DIM_1) :: MU_I
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: MU_E_DIM_1
    REAL(KIND=KIND ( 0.0D0 )), INTENT(IN), DIMENSION(MU_E_DIM_1) :: MU_E
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: NU_I_DIM_1
    REAL(KIND=KIND ( 0.0D0 )), INTENT(OUT), DIMENSION(NU_I_DIM_1) :: NU_I
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: NU_E_DIM_1
    REAL(KIND=KIND ( 0.0D0 )), INTENT(OUT), DIMENSION(NU_E_DIM_1) :: NU_E
  
    CALL NON(MU_I, MU_E, NU_I, NU_E)
  END SUBROUTINE C_NON
  

  
  SUBROUTINE C_NU(FACES_DIM_1, FACES_DIM_2, FACES, NODES_DIM_1, NODES_DIM_2, NODES, NORMALS_DIM_1, NORMALS_DIM_2, NORMALS, CENTRES_&
&DIM_1, CENTRES_DIM_2, CENTRES, S_DIM_1, S, NU_I_DIM_1, NU_I) BIND(C)
    USE BOUNDINGBOX_MODULE
    USE INTERSECT_AB_T_MODULE
    USE SHADOWING_MODULE, ONLY: NU
    IMPLICIT NONE
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: FACES_DIM_1
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: FACES_DIM_2
    INTEGER, INTENT(IN), DIMENSION(FACES_DIM_1,FACES_DIM_2) :: FACES
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: NODES_DIM_1
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: NODES_DIM_2
    REAL(KIND=KIND ( 0.0D0 )), INTENT(IN), DIMENSION(NODES_DIM_1,NODES_DIM_2) :: NODES
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: NORMALS_DIM_1
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: NORMALS_DIM_2
    REAL(KIND=KIND ( 0.0D0 )), INTENT(IN), DIMENSION(NORMALS_DIM_1,NORMALS_DIM_2) :: NORMALS
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: CENTRES_DIM_1
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: CENTRES_DIM_2
    REAL(KIND=KIND ( 0.0D0 )), INTENT(IN), DIMENSION(CENTRES_DIM_1,CENTRES_DIM_2) :: CENTRES
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: S_DIM_1
    REAL(KIND=KIND ( 0.0D0 )), INTENT(IN), DIMENSION(S_DIM_1) :: S
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: NU_I_DIM_1
    REAL(KIND=KIND ( 0.0D0 )), INTENT(INOUT), DIMENSION(NU_I_DIM_1) :: NU_I
  
    CALL NU(FACES, NODES, NORMALS, CENTRES, S, NU_I)
  END SUBROUTINE C_NU
  
END MODULE C_SHADOWING_MODULE

