#!/usr/bin/env python3

import fmodpy
import numpy as np

compute = fmodpy.fimport("src/Tests/compute.f90")

x = np.zeros((3,3), order='F')
y = np.zeros((3,3), order='F')
x[0,0] = 2.0
x[0,1] = 4.0

compute.compute_module.compute1(x, y)

print("x = ", x)
print("y = ", y)